const QUESTIONS = [
  {
    quest: "How many elements does a react component return?",
    opt1: "1 Element",
    opt2: "2 Elements",
    opt3: "Multiple Elements",
    opt4: "Inside vendor/",
    ans: "A",
  },
  {
    quest: "What is Babel?",
    opt1: "An interpreter",
    opt2: "An transpiler",
    opt3: "A Compiler",
    opt4: "Both Compiler and Transpilar",
    ans: "D",
  },
  {
    quest: "Everything in React is a _____________",
    opt1: "Module",
    opt2: "Component",
    opt3: "Package",
    opt4: "Class",
    ans: "B",
  },
  {
    quest: "Which of the following API is a MUST for every ReactJS component?",
    opt1: "renderComponent",
    opt2: "render",
    opt3: "getInitialState",
    opt4: "None of the Above",
    ans: "A",
  },
  {
    quest: "Props are __________ in other components",
    opt1: "injected",
    opt2: "methods",
    opt3: "A and B",
    opt4: "ALL",
    ans: "B",
  },
  {
    quest:
      "How can you access the state of a component from inside of a member function?",
    opt1: "this.getState()",
    opt2: "this.prototype.stateValue",
    opt3: "this.state",
    opt4: "this.values",
    ans: "C",
  },
  {
    quest: "What does the WEBPACK command do?",
    opt1: "Module bundler",
    opt2: "Runs react local development server.",
    opt3: "Transpiles all the Javascript down into one file",
    opt4: "None of the above",
    ans: "A",
  },
  {
    quest: "Which of the following API is a MUST for every ReactJS component?",
    opt1: "renderComponent",
    opt2: "render",
    opt3: "getInitialState",
    opt4: "None of the Above",
    ans: "A",
  },
  {
    quest: "Props are __________ in other components",
    opt1: "injected",
    opt2: "methods",
    opt3: "A and B",
    opt4: "1",
    ans: "ALL",
  },
  {
    quest:
      "How can you access the state of a component from inside of a member function?",
    opt1: "this.getState()",
    opt2: "this.prototype.stateValue",
    opt3: "this.state",
    opt4: "this.values",
    ans: "C",
  },
  {
    quest: "What is ReactJS?",
    opt1: "Server-side Framework",
    opt2: "User-interface framework",
    opt3: "A Library for building interaction interfaces",
    opt4: "None",
    ans: "C",
  },
];

export default QUESTIONS;
